on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python | PlatformIO
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - run: |
        pip install --upgrade pip
        pip install platformio

    - name: Static analysis
      run: cppcheck src include --enable=all --inconclusive --quiet

    - name: Build Firmware
      run: pio run

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: .pio/build/esp32dev/firmware.bin
