name: ESP32 PlatformIO CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Install cppcheck for static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck

    - name: Run static code analysis with cppcheck
      run: |
        cppcheck src include --enable=all --inconclusive --quiet || true

   # - name: Run PlatformIO unit tests
    #  run: pio test -v

    - name: Build firmware for esp32dev
      run: pio run -e esp32dev

    - name: List firmware build output
      run: ls -lah .pio/build/esp32dev/

    - name: Upload firmware artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: .pio/build/esp32dev/firmware.bin
